---
- name: redhat | installing keepalived
  yum:
    name: keepalived
    state: present
  become: true
  register: result
  until: result is succeeded
  when: ansible_distribution != "Fedora"

- name: redhat | installing keepalived
  dnf:
    name: keepalived
    state: present
  become: true
  register: result
  until: result is succeeded
  when: ansible_distribution == "Fedora"
